### ISSUE TITLE
possible compatability issue with zeek

### ISSUE THREAD

**Issue by ghost** [ncsa/bro-zeromq-writer#2]
Thank you for creating this great plugin, I appreciate any help you can provide. I have used bro/zeek for a couple of months but am new to zeromq. I followed the instructions [here](https://github.com/ncsa/bro-zeromq-writer) and have the plugin running, but I see some strange behavior and I cannot make it work as expected. I am using zeek-3.0.3 on Debian 9.

When I use `redef LogZeroMQ::endpoint = "tcp://127.0.0.1:12345";` in my `local.zeek` file and then tcpdump with `tcpdump -i lo port 12345 -nnn` I see a bunch of traffic originating from port 12345 but its scrolling through all the high level linux ports and the length appears to be 0. I see syn then ack, rst packets for each port.

I have also tried using `ipc:///tmp/zeek` as the endpoint and I never see the socket created on the filesystem.

I also tried subscribing with this python script and it seems to print a json log line at random times:
```
import zmq

# Socket to talk to server
context = zmq.Context()
socket = context.socket(zmq.SUB)

socket.connect("tcp://127.0.0.1:12345")

socket.setsockopt(zmq.SUBSCRIBE, "")

while True:
    print("{0}".format(socket.recv()))
```

What am I doing wrong here?

**Comment by JustinAzoff** [comment]
You actually need to listen in your subscriber program, not connect.. this should work:

```
import zmq

# Socket to talk to server
context = zmq.Context()
socket = context.socket(zmq.SUB)

socket.bind("tcp://127.0.0.1:12345")

socket.setsockopt(zmq.SUBSCRIBE, "*")

while True:
    print("{0}".format(socket.recv()))
```

**Comment by ghost** [comment]
I had to change "*" to "" in the setsockopt function, but everything is working like it should now. Here is the final code snippet that worked:
```
import zmq

# Socket to talk to server
context = zmq.Context()
socket = context.socket(zmq.SUB)

socket.bind("tcp://127.0.0.1:12345")

socket.setsockopt(zmq.SUBSCRIBE, "")

while True:
    print("{0}".format(socket.recv()))
```

Thank you for the prompt reply and your help!
